name: 构建Android APK

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'  # 当推送带v开头的标签时触发，例如v1.0.0
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: gradle

      - name: 创建Gradle Wrapper
        run: |
          mkdir -p gradle/wrapper
          echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties

      - name: 生成Gradle Wrapper JAR
        run: |
          mkdir -p gradle/wrapper
          curl -o gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/v7.6.0/gradle/wrapper/gradle-wrapper.jar

      - name: 创建项目级build.gradle文件
        run: |
          cat > build.gradle << 'EOF'
          // Top-level build file where you can add configuration options common to all sub-projects/modules.
          buildscript {
              repositories {
                  google()
                  mavenCentral()
              }
              dependencies {
                  classpath 'com.android.tools.build:gradle:7.4.2'
                  // NOTE: Do not place your application dependencies here; they belong
                  // in the individual module build.gradle files
              }
          }

          allprojects {
              repositories {
                  google()
                  mavenCentral()
              }
          }

          task clean(type: Delete) {
              delete rootProject.buildDir
          }
          EOF

      - name: 创建Gradlew脚本
        run: |
          echo '#!/usr/bin/env sh' > gradlew
          echo 'exec gradle "$@"' >> gradlew
          chmod +x gradlew

      - name: 创建本地属性文件
        run: touch local.properties

      - name: 创建gradle.properties文件
        run: |
          cat > gradle.properties << 'EOF'
          # Project-wide Gradle settings.
          
          # AndroidX package structure to make it clearer which packages are bundled with the
          # Android operating system, and which are packaged with your app's APK
          # https://developer.android.com/topic/libraries/support-library/androidx-rn
          android.useAndroidX=true
          
          # Automatically convert third-party libraries to use AndroidX
          android.enableJetifier=true
          
          # Kotlin code style for this project: "official" or "obsolete":
          kotlin.code.style=official
          
          # Enables namespacing of each library's R class so that its R class includes only the
          # resources declared in the library itself and none from the library's dependencies,
          # thereby reducing the size of the R class for that library
          android.nonTransitiveRClass=true
          
          # 配置Gradle使用更少的内存
          org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
          
          # 启用Gradle守护进程
          org.gradle.daemon=true
          
          # 启用并行构建
          org.gradle.parallel=true
          
          # 启用构建缓存
          org.gradle.caching=true
          EOF

      - name: 创建调试签名密钥
        run: |
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

      - name: 创建修改后的app/build.gradle文件
        run: |
          cat > app/build.gradle << 'EOF'
          plugins {
              id 'com.android.application'
          }

          android {
              compileSdkVersion 33
              
              signingConfigs {
                  release {
                      storeFile file("../debug.keystore")
                      storePassword "android"
                      keyAlias "androiddebugkey"
                      keyPassword "android"
                  }
              }
              
              defaultConfig {
                  applicationId "com.mostuseless.program"
                  minSdkVersion 21
                  targetSdkVersion 33
                  versionCode 1
                  versionName "1.0"
              }
              
              buildTypes {
                  release {
                      signingConfig signingConfigs.release
                      minifyEnabled false
                      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                  }
                  debug {
                      signingConfig signingConfigs.release
                  }
              }
              
              compileOptions {
                  sourceCompatibility JavaVersion.VERSION_1_8
                  targetCompatibility JavaVersion.VERSION_1_8
              }
          }

          dependencies {
              implementation 'androidx.appcompat:appcompat:1.6.1'
              implementation 'com.google.android.material:material:1.9.0'
              implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
          }
          EOF

      - name: 创建ProGuard规则文件
        run: |
          mkdir -p app/src/main
          cat > app/proguard-rules.pro << 'EOF'
          # 保留基本规则
          -keepattributes *Annotation*
          -keepattributes SourceFile,LineNumberTable
          -keep public class * extends java.lang.Exception
          
          # 应用程序特定规则
          -keep class com.mostuseless.program.** { *; }
          EOF

      - name: 创建资源目录
        run: |
          mkdir -p app/src/main/res/mipmap-hdpi
          mkdir -p app/src/main/res/mipmap-mdpi
          mkdir -p app/src/main/res/mipmap-xhdpi
          mkdir -p app/src/main/res/mipmap-xxhdpi
          mkdir -p app/src/main/res/mipmap-xxxhdpi
          mkdir -p app/src/main/res/values

      - name: 创建基本资源文件
        run: |
          # 创建styles.xml
          cat > app/src/main/res/values/styles.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <resources>
              <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
                  <item name="colorPrimary">#3F51B5</item>
                  <item name="colorPrimaryDark">#303F9F</item>
                  <item name="colorAccent">#FF4081</item>
              </style>
          </resources>
          EOF
          
          # 创建colors.xml
          cat > app/src/main/res/values/colors.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <resources>
              <color name="purple_200">#FFBB86FC</color>
              <color name="purple_500">#FF6200EE</color>
              <color name="purple_700">#FF3700B3</color>
              <color name="teal_200">#FF03DAC5</color>
              <color name="teal_700">#FF018786</color>
              <color name="black">#FF000000</color>
              <color name="white">#FFFFFFFF</color>
              <color name="ic_launcher_background">#3DDC84</color>
              <color name="ic_launcher_foreground">#FFFFFF</color>
          </resources>
          EOF
          
          # 创建向量图标文件 (XML格式)
          cat > app/src/main/res/mipmap-hdpi/ic_launcher.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <vector xmlns:android="http://schemas.android.com/apk/res/android"
              android:width="1024dp"
              android:height="1024dp"
              android:viewportWidth="1024"
              android:viewportHeight="1024">

              <path
                  android:fillColor="#000000"
                  android:pathData="M508.587,779.947 L271.36,643.413 L271.36,370.346 L508.587,244.053
          L750.933,370.347 L750.933,643.413 L508.587,779.946 Z M324.267,614.4
          L510.293,721.92 L699.733,614.4 L699.733,401.067 L508.587,302.08 L324.267,401.067
          L324.267,614.4 Z" />
              <path
                  android:fillColor="#000000"
                  android:pathData="M512,515.413 L302.08,416.427 L322.56,370.347 L512,459.093 L708.267,370.347
          L728.747,416.427 Z" />
              <path
                  android:fillColor="#000000"
                  android:pathData="M486.4,488.107 L537.6,488.107 L537.6,747.52 L486.4,747.52 Z" />
              <path
                  android:fillColor="#000000"
                  android:pathData="M512,1015.47 C233.813,1015.47,8.53333,790.187,8.53333,512
          S233.813,8.53333,512,8.53333 S1015.47,233.813,1015.47,512
          C1015.47,597.333,993.28,680.96,954.027,754.347
          C947.2,766.294,931.84,771.414,919.894,764.587 S902.827,742.4,909.654,730.454
          C945.494,663.894,965.974,588.801,965.974,513.707
          C964.267,262.827,761.174,59.734,512.001,59.734 S59.7333,262.827,59.7333,512
          S262.827,964.267,512,964.267 C592.213,964.267,670.72,943.787,738.987,902.827
          C750.934,896,766.294,899.414,774.827,911.36 S778.24,938.667,766.294,947.2
          C687.787,991.573,600.747,1015.47,512.001,1015.47 Z" />
              <path
                  android:fillColor="#000000"
                  android:pathData="M839.68,885.76 C832.853,885.76,826.027,882.347,820.907,877.227
          C810.667,866.987,812.374,849.92,822.614,841.387
          C827.734,836.267,834.561,831.147,839.681,824.32
          C849.921,814.08,865.281,814.08,875.521,824.32
          C885.761,834.56,885.761,849.92,875.521,860.16 L856.748,878.933
          C851.628,884.053,846.508,885.76,839.681,885.76 Z" />
          </vector>
          EOF
          
          # 创建圆形图标
          cat > app/src/main/res/mipmap-hdpi/ic_launcher_round.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <vector xmlns:android="http://schemas.android.com/apk/res/android"
              android:width="1024dp"
              android:height="1024dp"
              android:viewportWidth="1024"
              android:viewportHeight="1024">

              <path
                  android:fillColor="#000000"
                  android:pathData="M512,1015.47 C233.813,1015.47,8.53333,790.187,8.53333,512
          S233.813,8.53333,512,8.53333 S1015.47,233.813,1015.47,512
          S790.187,1015.47,512,1015.47 Z M508.587,779.947 L271.36,643.413 L271.36,370.346 L508.587,244.053
          L750.933,370.347 L750.933,643.413 L508.587,779.946 Z M324.267,614.4
          L510.293,721.92 L699.733,614.4 L699.733,401.067 L508.587,302.08 L324.267,401.067
          L324.267,614.4 Z" />
              <path
                  android:fillColor="#000000"
                  android:pathData="M512,515.413 L302.08,416.427 L322.56,370.347 L512,459.093 L708.267,370.347
          L728.747,416.427 Z" />
              <path
                  android:fillColor="#000000"
                  android:pathData="M486.4,488.107 L537.6,488.107 L537.6,747.52 L486.4,747.52 Z" />
          </vector>
          EOF
          
          # 复制到其他尺寸目录
          cp app/src/main/res/mipmap-hdpi/ic_launcher.xml app/src/main/res/mipmap-mdpi/ic_launcher.xml
          cp app/src/main/res/mipmap-hdpi/ic_launcher.xml app/src/main/res/mipmap-xhdpi/ic_launcher.xml
          cp app/src/main/res/mipmap-hdpi/ic_launcher.xml app/src/main/res/mipmap-xxhdpi/ic_launcher.xml
          cp app/src/main/res/mipmap-hdpi/ic_launcher.xml app/src/main/res/mipmap-xxxhdpi/ic_launcher.xml
          
          cp app/src/main/res/mipmap-hdpi/ic_launcher_round.xml app/src/main/res/mipmap-mdpi/ic_launcher_round.xml
          cp app/src/main/res/mipmap-hdpi/ic_launcher_round.xml app/src/main/res/mipmap-xhdpi/ic_launcher_round.xml
          cp app/src/main/res/mipmap-hdpi/ic_launcher_round.xml app/src/main/res/mipmap-xxhdpi/ic_launcher_round.xml
          cp app/src/main/res/mipmap-hdpi/ic_launcher_round.xml app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.xml
          
          # 创建strings.xml
          cat > app/src/main/res/values/strings.xml << 'EOF'
          <resources>
              <string name="app_name">最没用的程序</string>
          </resources>
          EOF

      - name: 创建Java源文件目录
        run: mkdir -p app/src/main/java/com/mostuseless/program

      - name: 创建AndroidManifest.xml
        run: |
          cat > app/src/main/AndroidManifest.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.mostuseless.program">

              <application
                  android:allowBackup="false"
                  android:icon="@mipmap/ic_launcher"
                  android:label="@string/app_name"
                  android:roundIcon="@mipmap/ic_launcher_round"
                  android:supportsRtl="true"
                  android:theme="@style/AppTheme">
                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:excludeFromRecents="true"
                      android:noHistory="true"
                      android:finishOnTaskLaunch="true"
                      android:clearTaskOnLaunch="true"
                      android:stateNotNeeded="true"
                      android:launchMode="singleInstance">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>

          </manifest>
          EOF

      - name: 创建MainActivity.java
        run: |
          cat > app/src/main/java/com/mostuseless/program/MainActivity.java << 'EOF'
          package com.mostuseless.program;

          import android.app.Activity;
          import android.os.Bundle;

          public class MainActivity extends Activity {

              @Override
              protected void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  
                  // 立即结束当前活动，不设置任何内容视图
                  finish();
                  
                  // 确保应用完全退出，不留后台进程
                  android.os.Process.killProcess(android.os.Process.myPid());
                  System.exit(0);
              }
              
              @Override
              protected void onResume() {
                  super.onResume();
                  // 如果因某种原因活动被恢复，立即退出
                  finish();
                  android.os.Process.killProcess(android.os.Process.myPid());
                  System.exit(0);
              }
          }
          EOF

      - name: 创建activity_main.xml
        run: |
          mkdir -p app/src/main/res/layout
          cat > app/src/main/res/layout/activity_main.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              xmlns:tools="http://schemas.android.com/tools"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              tools:context=".MainActivity">

              <TextView
                  android:layout_width="wrap_content"
                  android:layout_height="wrap_content"
                  android:text="正在退出应用..."
                  android:textSize="24sp"
                  app:layout_constraintBottom_toBottomOf="parent"
                  app:layout_constraintLeft_toLeftOf="parent"
                  app:layout_constraintRight_toRightOf="parent"
                  app:layout_constraintTop_toTopOf="parent" />

          </androidx.constraintlayout.widget.ConstraintLayout>
          EOF

      - name: 构建Debug APK
        run: ./gradlew assembleDebug

      - name: 构建Release APK
        run: ./gradlew assembleRelease

      - name: 重命名Release APK
        run: |
          mkdir -p artifacts
          cp app/build/outputs/apk/release/app-release.apk artifacts/auto-exit-app-release.apk
          cp app/build/outputs/apk/debug/app-debug.apk artifacts/auto-exit-app-debug.apk

      - name: 上传Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: artifacts/auto-exit-app-debug.apk

      - name: 上传Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: artifacts/auto-exit-app-release.apk

      # 如果是标签推送，则创建Release
      - name: 创建GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/auto-exit-app-release.apk
            artifacts/auto-exit-app-debug.apk
          name: Release ${{ github.ref_name }}
          body: |
            # 最没用的程序 - 版本 ${{ github.ref_name }}
            
            这是一个自动退出的Android应用，在启动后会立即自动退出，不会保留任何后台进程。
            
            ## 下载
            
            - [Release版本APK](artifacts/auto-exit-app-release.apk)
            - [Debug版本APK](artifacts/auto-exit-app-debug.apk)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
